### YamlMime:ManagedReference
items:
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  commentId: T:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  id: QueueProcessorOptionsProvider
  parent: ReflectionEventing.DependencyInjection.Configuration
  children:
  - ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor(ReflectionEventing.EventBusBuilderOptions,System.Object)
  - ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
  - ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
  langs:
  - csharp
  - vb
  name: QueueProcessorOptionsProvider
  nameWithType: QueueProcessorOptionsProvider
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  type: Class
  source:
    remote:
      path: src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
      branch: main
      repo: https://github.com/lepoco/reflectioneventing.git
    id: QueueProcessorOptionsProvider
    path: ../src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
    startLine: 10
  assemblies:
  - ReflectionEventing.DependencyInjection
  namespace: ReflectionEventing.DependencyInjection.Configuration
  summary: Provides configuration options for the queue processor.
  example: []
  syntax:
    content: public sealed class QueueProcessorOptionsProvider
    content.vb: Public NotInheritable Class QueueProcessorOptionsProvider
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor(ReflectionEventing.EventBusBuilderOptions,System.Object)
  commentId: M:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor(ReflectionEventing.EventBusBuilderOptions,System.Object)
  id: '#ctor(ReflectionEventing.EventBusBuilderOptions,System.Object)'
  parent: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  langs:
  - csharp
  - vb
  name: QueueProcessorOptionsProvider(EventBusBuilderOptions, object?)
  nameWithType: QueueProcessorOptionsProvider.QueueProcessorOptionsProvider(EventBusBuilderOptions, object?)
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.QueueProcessorOptionsProvider(ReflectionEventing.EventBusBuilderOptions, object?)
  type: Constructor
  source:
    remote:
      path: src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
      branch: main
      repo: https://github.com/lepoco/reflectioneventing.git
    id: .ctor
    path: ../src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
    startLine: 10
  assemblies:
  - ReflectionEventing.DependencyInjection
  namespace: ReflectionEventing.DependencyInjection.Configuration
  summary: Provides configuration options for the queue processor.
  example: []
  syntax:
    content: public QueueProcessorOptionsProvider(EventBusBuilderOptions options, object? serviceKey = null)
    parameters:
    - id: options
      type: ReflectionEventing.EventBusBuilderOptions
    - id: serviceKey
      type: System.Object
    content.vb: Public Sub New(options As EventBusBuilderOptions, serviceKey As Object = Nothing)
  overload: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor*
  nameWithType.vb: QueueProcessorOptionsProvider.New(EventBusBuilderOptions, Object)
  fullName.vb: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.New(ReflectionEventing.EventBusBuilderOptions, Object)
  name.vb: New(EventBusBuilderOptions, Object)
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
  commentId: P:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
  id: Value
  parent: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: QueueProcessorOptionsProvider.Value
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
  type: Property
  source:
    remote:
      path: src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
      branch: main
      repo: https://github.com/lepoco/reflectioneventing.git
    id: Value
    path: ../src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
    startLine: 18
  assemblies:
  - ReflectionEventing.DependencyInjection
  namespace: ReflectionEventing.DependencyInjection.Configuration
  summary: Gets the configuration options for the queue processor.
  example: []
  syntax:
    content: public EventBusBuilderOptions Value { get; }
    parameters: []
    return:
      type: ReflectionEventing.EventBusBuilderOptions
    content.vb: Public ReadOnly Property Value As EventBusBuilderOptions
  overload: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value*
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
  commentId: P:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
  id: ServiceKey
  parent: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider
  langs:
  - csharp
  - vb
  name: ServiceKey
  nameWithType: QueueProcessorOptionsProvider.ServiceKey
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
  type: Property
  source:
    remote:
      path: src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
      branch: main
      repo: https://github.com/lepoco/reflectioneventing.git
    id: ServiceKey
    path: ../src/ReflectionEventing.DependencyInjection/Configuration/QueueProcessorOptionsProvider.cs
    startLine: 26
  assemblies:
  - ReflectionEventing.DependencyInjection
  namespace: ReflectionEventing.DependencyInjection.Configuration
  summary: Gets the service key associated with the queue processor options.
  example: []
  syntax:
    content: public object? ServiceKey { get; }
    parameters: []
    return:
      type: System.Object
    content.vb: Public ReadOnly Property ServiceKey As Object
  overload: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey*
references:
- uid: ReflectionEventing.DependencyInjection.Configuration
  commentId: N:ReflectionEventing.DependencyInjection.Configuration
  href: ReflectionEventing.html
  name: ReflectionEventing.DependencyInjection.Configuration
  nameWithType: ReflectionEventing.DependencyInjection.Configuration
  fullName: ReflectionEventing.DependencyInjection.Configuration
  spec.csharp:
  - uid: ReflectionEventing
    name: ReflectionEventing
    href: ReflectionEventing.html
  - name: .
  - uid: ReflectionEventing.DependencyInjection
    name: DependencyInjection
    href: ReflectionEventing.DependencyInjection.html
  - name: .
  - uid: ReflectionEventing.DependencyInjection.Configuration
    name: Configuration
    href: ReflectionEventing.DependencyInjection.Configuration.html
  spec.vb:
  - uid: ReflectionEventing
    name: ReflectionEventing
    href: ReflectionEventing.html
  - name: .
  - uid: ReflectionEventing.DependencyInjection
    name: DependencyInjection
    href: ReflectionEventing.DependencyInjection.html
  - name: .
  - uid: ReflectionEventing.DependencyInjection.Configuration
    name: Configuration
    href: ReflectionEventing.DependencyInjection.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor*
  commentId: Overload:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.#ctor
  href: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.html#ReflectionEventing_DependencyInjection_Configuration_QueueProcessorOptionsProvider__ctor_ReflectionEventing_EventBusBuilderOptions_System_Object_
  name: QueueProcessorOptionsProvider
  nameWithType: QueueProcessorOptionsProvider.QueueProcessorOptionsProvider
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.QueueProcessorOptionsProvider
  nameWithType.vb: QueueProcessorOptionsProvider.New
  fullName.vb: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.New
  name.vb: New
- uid: ReflectionEventing.EventBusBuilderOptions
  commentId: T:ReflectionEventing.EventBusBuilderOptions
  parent: ReflectionEventing
  href: ReflectionEventing.EventBusBuilderOptions.html
  name: EventBusBuilderOptions
  nameWithType: EventBusBuilderOptions
  fullName: ReflectionEventing.EventBusBuilderOptions
- uid: ReflectionEventing
  commentId: N:ReflectionEventing
  href: ReflectionEventing.html
  name: ReflectionEventing
  nameWithType: ReflectionEventing
  fullName: ReflectionEventing
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value*
  commentId: Overload:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
  href: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.html#ReflectionEventing_DependencyInjection_Configuration_QueueProcessorOptionsProvider_Value
  name: Value
  nameWithType: QueueProcessorOptionsProvider.Value
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.Value
- uid: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey*
  commentId: Overload:ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
  href: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.html#ReflectionEventing_DependencyInjection_Configuration_QueueProcessorOptionsProvider_ServiceKey
  name: ServiceKey
  nameWithType: QueueProcessorOptionsProvider.ServiceKey
  fullName: ReflectionEventing.DependencyInjection.Configuration.QueueProcessorOptionsProvider.ServiceKey
